[mypy]
files = vrs_nesting
check_untyped_defs = True
no_implicit_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True

[mypy-ezdxf.*]
ignore_missing_imports = True

[mypy-shapely.*]
ignore_missing_imports = True
