use crate::geometry::EPS;
use crate::sheet::SheetShape;

/// Candidate point for item placement. `(x, y)` is the bbox-min corner
/// at which the next item's bounding box would be tried.
#[derive(Debug, Clone)]
pub struct CandidatePoint {
    pub sheet_index: usize,
    pub x: f64,
    pub y: f64,
}

/// Axis-aligned placed bounding box (bbox-min coords, Phase 1 rectangular items only).
#[derive(Debug, Clone)]
pub struct PlacedBbox {
    pub sheet_index: usize,
    pub x1: f64,
    pub y1: f64,
    pub x2: f64,
    pub y2: f64,
}

impl PlacedBbox {
    // QUALITY_RISK: BboxOnlyProxy
    // Exact for: Phase 1 rectangular items at 0/90/180/270° (AABB overlap == true overlap)
    // Proxy for: irregular shapes where axis-aligned bbox overapproximates true shape
    // Parity: PROXY (F04, SGH-Q00)
    /// Rect-rect overlap — exact for Phase 1 rectangular items at 0/90/180/270°.
    pub fn overlaps(&self, other: &PlacedBbox) -> bool {
        if self.sheet_index != other.sheet_index {
            return false;
        }
        self.x1 < other.x2 - EPS
            && self.x2 > other.x1 + EPS
            && self.y1 < other.y2 - EPS
            && self.y2 > other.y1 + EPS
    }
}

/// Source classification for candidates generated by `generate_candidates_with_sheets`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CandidateSource {
    /// Sheet origin (0, 0) — legacy rectangular BLF behavior.
    Origin,
    /// Right/top/top-right corner of a placed bbox — legacy neighbor cascade.
    PlacedNeighbor,
    /// Outer polygon vertex of an irregular sheet boundary.
    VertexNear,
    /// Midpoint of an outer polygon edge of an irregular sheet boundary.
    EdgeNear,
    /// Grid sample inside the sheet bbox — deterministic interior sampling.
    InteriorSample,
}

/// Candidate count breakdown from `generate_candidates_with_sheets`.
#[derive(Debug, Clone, Default)]
pub struct CandidateGenerationStats {
    /// Total candidate count after sort+dedup.
    pub total: usize,
    /// Candidates from sheet origins (one per sheet).
    pub from_origin: usize,
    /// Candidates from placed bbox right/top/top-right corners.
    pub from_neighbor: usize,
    /// Candidates from irregular sheet polygon vertices.
    pub from_vertex: usize,
    /// Candidates from irregular sheet polygon edge midpoints.
    pub from_edge: usize,
    /// Candidates from interior grid sampling of irregular sheets.
    pub from_interior: usize,
}

impl CandidateGenerationStats {
    pub fn summary(&self) -> String {
        format!(
            "total={} origin={} neighbor={} vertex={} edge={} interior={}",
            self.total,
            self.from_origin,
            self.from_neighbor,
            self.from_vertex,
            self.from_edge,
            self.from_interior,
        )
    }
}

/// Grid divisions for interior sampling: (INTERIOR_GRID_STEPS-1) × (INTERIOR_GRID_STEPS-1)
/// sample points per irregular sheet bbox (e.g. 5 → 4×4 = up to 16 interior points).
const INTERIOR_GRID_STEPS: usize = 5;
/// Minimum step size to avoid degenerate grids on very small sheets.
const MIN_STEP: f64 = 1.0;

/// Irregular-aware candidate generation.
///
/// For each sheet: generates origin and placed-neighbor points (legacy rectangular behavior).
/// Additionally, for irregular sheets (`has_irregular_outer = true`):
///   - **vertex_near**: each outer polygon vertex as a bbox-min candidate;
///   - **edge_near**: midpoint of each outer polygon edge;
///   - **interior_sample**: deterministic grid across the sheet bbox.
///
/// Sorted by `(sheet_index ASC, y ASC, x ASC)`, deduplicated by EPS proximity.
/// The `CandidateGenerationStats` counts raw candidates before dedup, except `total` which
/// reflects the post-dedup count.
///
/// All candidate points are bbox-min positions; boundary validity is enforced later in the
/// construction/repair loops via `boundary::rect_within_boundary`.
pub fn generate_candidates_with_sheets(
    sheets: &[SheetShape],
    placed: &[PlacedBbox],
) -> (Vec<CandidatePoint>, CandidateGenerationStats) {
    let mut stats = CandidateGenerationStats::default();
    let mut pts: Vec<CandidatePoint> = Vec::new();

    // Legacy: one origin per sheet.
    for s in 0..sheets.len() {
        pts.push(CandidatePoint {
            sheet_index: s,
            x: 0.0,
            y: 0.0,
        });
        stats.from_origin += 1;
    }

    // Legacy: placed bbox right/top/top-right corners (PlacedNeighbor).
    for pb in placed {
        pts.push(CandidatePoint {
            sheet_index: pb.sheet_index,
            x: pb.x2,
            y: pb.y1,
        });
        pts.push(CandidatePoint {
            sheet_index: pb.sheet_index,
            x: pb.x1,
            y: pb.y2,
        });
        pts.push(CandidatePoint {
            sheet_index: pb.sheet_index,
            x: pb.x2,
            y: pb.y2,
        });
        stats.from_neighbor += 3;
    }

    // Irregular: vertex-near, edge-near, interior samples.
    for (s, sheet) in sheets.iter().enumerate() {
        if !sheet.has_irregular_outer || sheet.outer_vertices.is_empty() {
            continue;
        }
        let verts = &sheet.outer_vertices;
        let n = verts.len();

        // VertexNear: each polygon vertex is a candidate bbox-min.
        for v in verts {
            pts.push(CandidatePoint {
                sheet_index: s,
                x: v.x,
                y: v.y,
            });
            stats.from_vertex += 1;
        }

        // EdgeNear: midpoint of each polygon edge.
        for i in 0..n {
            let a = verts[i];
            let b = verts[(i + 1) % n];
            pts.push(CandidatePoint {
                sheet_index: s,
                x: (a.x + b.x) * 0.5,
                y: (a.y + b.y) * 0.5,
            });
            stats.from_edge += 1;
        }

        // InteriorSample: uniform grid over the sheet bbox.
        // Points at (min_x + k*step_x) × (min_y + k*step_y), k = 1, 2, ...,  < max.
        let step_x = (sheet.width / INTERIOR_GRID_STEPS as f64).max(MIN_STEP);
        let step_y = (sheet.height / INTERIOR_GRID_STEPS as f64).max(MIN_STEP);
        let mut y = sheet.min_y + step_y;
        while y < sheet.max_y {
            let mut x = sheet.min_x + step_x;
            while x < sheet.max_x {
                pts.push(CandidatePoint {
                    sheet_index: s,
                    x,
                    y,
                });
                stats.from_interior += 1;
                x += step_x;
            }
            y += step_y;
        }
    }

    // Sort and dedup — same policy as generate_candidates.
    pts.sort_by(|a, b| {
        a.sheet_index
            .cmp(&b.sheet_index)
            .then_with(|| a.y.partial_cmp(&b.y).unwrap_or(std::cmp::Ordering::Equal))
            .then_with(|| a.x.partial_cmp(&b.x).unwrap_or(std::cmp::Ordering::Equal))
    });
    pts.dedup_by(|a, b| {
        a.sheet_index == b.sheet_index && (a.x - b.x).abs() < EPS && (a.y - b.y).abs() < EPS
    });

    stats.total = pts.len();
    (pts, stats)
}

/// Generate sorted, deduplicated placement candidate points.
///
/// Each sheet contributes the origin `(0, 0)`. Each placed bbox contributes
/// its right-side, top-side, and top-right-corner points.
/// Result sorted by `(sheet_index ASC, y ASC, x ASC)`, deduplicated by EPS proximity.
///
/// For irregular/remnant stocks, prefer `generate_candidates_with_sheets` which also
/// generates vertex-near, edge-near, and interior sampling candidates.
pub fn generate_candidates(sheet_count: usize, placed: &[PlacedBbox]) -> Vec<CandidatePoint> {
    let mut pts: Vec<CandidatePoint> = Vec::with_capacity(sheet_count + placed.len() * 3);
    for s in 0..sheet_count {
        pts.push(CandidatePoint {
            sheet_index: s,
            x: 0.0,
            y: 0.0,
        });
    }
    for pb in placed {
        pts.push(CandidatePoint {
            sheet_index: pb.sheet_index,
            x: pb.x2,
            y: pb.y1,
        });
        pts.push(CandidatePoint {
            sheet_index: pb.sheet_index,
            x: pb.x1,
            y: pb.y2,
        });
        pts.push(CandidatePoint {
            sheet_index: pb.sheet_index,
            x: pb.x2,
            y: pb.y2,
        });
    }
    pts.sort_by(|a, b| {
        a.sheet_index
            .cmp(&b.sheet_index)
            .then_with(|| a.y.partial_cmp(&b.y).unwrap_or(std::cmp::Ordering::Equal))
            .then_with(|| a.x.partial_cmp(&b.x).unwrap_or(std::cmp::Ordering::Equal))
    });
    pts.dedup_by(|a, b| {
        a.sheet_index == b.sheet_index && (a.x - b.x).abs() < EPS && (a.y - b.y).abs() < EPS
    });
    pts
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::geometry::PointInput;
    use crate::sheet::{expand_sheets, Stock};

    fn l_shape_sheets() -> Vec<SheetShape> {
        let stock = Stock {
            id: "L".to_string(),
            quantity: 1,
            width: None,
            height: None,
            outer_points: Some(vec![
                PointInput::Pair([0.0, 0.0]),
                PointInput::Pair([100.0, 0.0]),
                PointInput::Pair([100.0, 50.0]),
                PointInput::Pair([50.0, 50.0]),
                PointInput::Pair([50.0, 100.0]),
                PointInput::Pair([0.0, 100.0]),
            ]),
            holes_points: None,
            cost_per_use: None,
        };
        expand_sheets(&[stock]).expect("expand_sheets")
    }

    fn rect_sheets(w: f64, h: f64) -> Vec<SheetShape> {
        let stock = Stock {
            id: "R".to_string(),
            quantity: 1,
            width: Some(w),
            height: Some(h),
            outer_points: None,
            holes_points: None,
            cost_per_use: None,
        };
        expand_sheets(&[stock]).expect("expand_sheets")
    }

    #[test]
    fn irregular_candidates_include_vertex_edge_interior() {
        let sheets = l_shape_sheets();
        let (cands, stats) = generate_candidates_with_sheets(&sheets, &[]);
        assert!(stats.from_vertex > 0, "must have vertex-near candidates");
        assert!(stats.from_edge > 0, "must have edge-near candidates");
        assert!(
            stats.from_interior > 0,
            "must have interior sample candidates"
        );
        assert_eq!(
            stats.total,
            cands.len(),
            "stats.total must match actual count"
        );
        assert!(stats.total > 1, "must have more than just origin");
    }

    #[test]
    fn irregular_candidates_more_than_legacy() {
        let sheets = l_shape_sheets();
        let legacy = generate_candidates(1, &[]);
        let (irregular, _) = generate_candidates_with_sheets(&sheets, &[]);
        assert!(
            irregular.len() > legacy.len(),
            "irregular-aware must produce more candidates than legacy for L-shape: {} vs {}",
            irregular.len(),
            legacy.len()
        );
    }

    #[test]
    fn rectangular_sheets_no_irregular_sources() {
        let sheets = rect_sheets(100.0, 80.0);
        let (cands, stats) = generate_candidates_with_sheets(&sheets, &[]);
        assert_eq!(
            stats.from_vertex, 0,
            "rect stock: no vertex-near candidates"
        );
        assert_eq!(stats.from_edge, 0, "rect stock: no edge-near candidates");
        assert_eq!(stats.from_interior, 0, "rect stock: no interior candidates");
        assert_eq!(
            stats.from_origin, 1,
            "rect stock: exactly 1 origin candidate"
        );
        assert_eq!(
            cands.len(),
            1,
            "rect stock with no placed items: exactly 1 candidate"
        );
    }

    #[test]
    fn irregular_candidates_deterministic() {
        let sheets = l_shape_sheets();
        let placed = vec![PlacedBbox {
            sheet_index: 0,
            x1: 0.0,
            y1: 0.0,
            x2: 20.0,
            y2: 15.0,
        }];
        let (c1, _) = generate_candidates_with_sheets(&sheets, &placed);
        let (c2, _) = generate_candidates_with_sheets(&sheets, &placed);
        assert_eq!(c1.len(), c2.len(), "deterministic: same count");
        for (a, b) in c1.iter().zip(c2.iter()) {
            assert_eq!(a.sheet_index, b.sheet_index);
            assert!((a.x - b.x).abs() < 1e-12);
            assert!((a.y - b.y).abs() < 1e-12);
        }
    }

    #[test]
    fn candidates_origin_for_every_sheet() {
        let cands = generate_candidates(3, &[]);
        assert_eq!(cands.len(), 3);
        for s in 0..3 {
            assert!(cands
                .iter()
                .any(|c| c.sheet_index == s && c.x == 0.0 && c.y == 0.0));
        }
    }

    #[test]
    fn candidates_from_placed_bbox_adds_three_points() {
        let placed = vec![PlacedBbox {
            sheet_index: 0,
            x1: 0.0,
            y1: 0.0,
            x2: 100.0,
            y2: 50.0,
        }];
        let cands = generate_candidates(1, &placed);
        assert!(cands
            .iter()
            .any(|c| c.sheet_index == 0 && (c.x - 100.0).abs() < 1e-6 && c.y.abs() < 1e-6));
        assert!(cands
            .iter()
            .any(|c| c.sheet_index == 0 && c.x.abs() < 1e-6 && (c.y - 50.0).abs() < 1e-6));
        assert!(cands.iter().any(|c| c.sheet_index == 0
            && (c.x - 100.0).abs() < 1e-6
            && (c.y - 50.0).abs() < 1e-6));
    }

    #[test]
    fn candidates_sorted_by_sheet_y_x() {
        let placed = vec![PlacedBbox {
            sheet_index: 0,
            x1: 0.0,
            y1: 0.0,
            x2: 50.0,
            y2: 30.0,
        }];
        let cands = generate_candidates(2, &placed);
        for w in cands.windows(2) {
            let a = &w[0];
            let b = &w[1];
            let ok = a.sheet_index < b.sheet_index
                || (a.sheet_index == b.sheet_index && a.y < b.y + 1e-12)
                || (a.sheet_index == b.sheet_index
                    && (a.y - b.y).abs() < 1e-6
                    && a.x <= b.x + 1e-12);
            assert!(ok, "not sorted: ({},{}) vs ({},{})", a.x, a.y, b.x, b.y);
        }
    }

    #[test]
    fn placed_bbox_overlap_same_sheet() {
        let a = PlacedBbox {
            sheet_index: 0,
            x1: 0.0,
            y1: 0.0,
            x2: 50.0,
            y2: 50.0,
        };
        let b = PlacedBbox {
            sheet_index: 0,
            x1: 25.0,
            y1: 25.0,
            x2: 75.0,
            y2: 75.0,
        };
        assert!(a.overlaps(&b));
    }

    #[test]
    fn placed_bbox_no_overlap_adjacent() {
        let a = PlacedBbox {
            sheet_index: 0,
            x1: 0.0,
            y1: 0.0,
            x2: 50.0,
            y2: 50.0,
        };
        let b = PlacedBbox {
            sheet_index: 0,
            x1: 50.0,
            y1: 0.0,
            x2: 100.0,
            y2: 50.0,
        };
        assert!(!a.overlaps(&b));
    }

    #[test]
    fn placed_bbox_no_overlap_different_sheets() {
        let a = PlacedBbox {
            sheet_index: 0,
            x1: 0.0,
            y1: 0.0,
            x2: 50.0,
            y2: 50.0,
        };
        let b = PlacedBbox {
            sheet_index: 1,
            x1: 0.0,
            y1: 0.0,
            x2: 50.0,
            y2: 50.0,
        };
        assert!(!a.overlaps(&b));
    }
}
